twilio.settings:
  type: mapping
  label: Settings
  mapping:
    registration_form:
      type: integer
    account:
      type: string
    token:
      type: string
    number:
      type: string
    country_codes:
      type: string
    registration_form:
      type: integer
    long_sms:
      type: integer
